#pragma once

class Entity;

enum EDITOR_THEME
{
    EDITOR_THEME_NONE,
    EDITOR_THEME_DARK,
    EDITOR_THEME_DARK_OTHER,
    EDITOR_THEME_COUNT,
};

enum EDITOR_CURSOR_TYPE
{
    EDITOR_CURSOR_TYPE_ARROW,
    EDITOR_CURSOR_TYPE_RIGHT_ARROW,
    EDITOR_CURSOR_TYPE_CROSS,
    EDITOR_CURSOR_TYPE_BULLSEYE,
    EDITOR_CURSOR_TYPE_HAND,
    EDITOR_CURSOR_TYPE_IBEAM,
    EDITOR_CURSOR_TYPE_SIZE_NS,
    EDITOR_CURSOR_TYPE_SIZE_WE,
    EDITOR_CURSOR_TYPE_SIZE_NESW,
    EDITOR_CURSOR_TYPE_SIZE_NWSE,
    EDITOR_CURSOR_TYPE_SIZING,
    EDITOR_CURSOR_TYPE_MAGNIFIER,
    EDITOR_CURSOR_TYPE_COUNT,
};

enum EDITOR_VIEWPORT_LAYOUT
{
    EDITOR_VIEWPORT_LAYOUT_1X1,         // 1 viewport, perspective by default
    EDITOR_VIEWPORT_LAYOUT_2X2,         // 4 viewports, from top-left to bottom-right, top, front, side, perspective
    EDITOR_VIEWPORT_LAYOUT_COUNT,
};

enum EDITOR_EDIT_MODE
{
    EDITOR_EDIT_MODE_NONE,
    EDITOR_EDIT_MODE_MAP,
    EDITOR_EDIT_MODE_ENTITY,
    EDITOR_EDIT_MODE_GEOMETRY,
    EDITOR_EDIT_MODE_TERRAIN,
    EDITOR_EDIT_MODE_COUNT,
};

enum EDITOR_ENTITY_EDIT_MODE_WIDGET
{
    EDITOR_ENTITY_EDIT_MODE_WIDGET_SELECT,
    EDITOR_ENTITY_EDIT_MODE_WIDGET_MOVE,
    EDITOR_ENTITY_EDIT_MODE_WIDGET_ROTATE,
    EDITOR_ENTITY_EDIT_MODE_WIDGET_SCALE,
    EDITOR_ENTITY_EDIT_MODE_WIDGET_COUNT,
};

enum EDITOR_BLOCK_TERRAIN_EDIT_MODE_WIDGET
{
    EDITOR_BLOCK_TERRAIN_EDIT_MODE_WIDGET_SELECT,
    EDITOR_BLOCK_TERRAIN_EDIT_MODE_WIDGET_PLACE,
    EDITOR_BLOCK_TERRAIN_EDIT_MODE_WIDGET_DELETE,
    EDITOR_BLOCK_TERRAIN_EDIT_MODE_WIDGET_COUNT,
};

enum EDITOR_TERRAIN_EDIT_MODE_WIDGET
{
    EDITOR_HEIGHTFIELD_TERRAIN_EDIT_MODE_WIDGET_EDIT_HEIGHT,
    EDITOR_HEIGHTFIELD_TERRAIN_EDIT_MODE_WIDGET_EDIT_LAYERS,
    EDITOR_HEIGHTFIELD_TERRAIN_EDIT_MODE_WIDGET_EDIT_DETAILS,
    EDITOR_HEIGHTFIELD_TERRAIN_EDIT_MODE_WIDGET_EDIT_HOLES,
    EDITOR_HEIGHTFIELD_TERRAIN_EDIT_MODE_WIDGET_EDIT_SECTIONS,
    EDITOR_HEIGHTFIELD_TERRAIN_EDIT_MODE_WIDGET_IMPORT_HEIGHTMAP,
    EDITOR_HEIGHTFIELD_TERRAIN_EDIT_MODE_WIDGET_SETTINGS,
    EDITOR_HEIGHTFIELD_TERRAIN_EDIT_MODE_WIDGET_COUNT,
};

enum EDITOR_REFERENCE_COORDINATE_SYSTEM
{
    EDITOR_REFERENCE_COORDINATE_SYSTEM_LOCAL,
    EDITOR_REFERENCE_COORDINATE_SYSTEM_WORLD,
    EDITOR_REFERENCE_COORDINATE_SYSTEM_COUNT,
};

enum EDITOR_CAMERA_MODE
{
    EDITOR_CAMERA_MODE_ORTHOGRAPHIC_FRONT,
    EDITOR_CAMERA_MODE_ORTHOGRAPHIC_SIDE,
    EDITOR_CAMERA_MODE_ORTHOGRAPHIC_TOP,
    EDITOR_CAMERA_MODE_ISOMETRIC,
    EDITOR_CAMERA_MODE_PERSPECTIVE,
    EDITOR_CAMERA_MODE_ARCBALL,
    EDITOR_CAMERA_MODE_COUNT,
};

enum EDITOR_RENDER_MODE
{
    EDITOR_RENDER_MODE_WIREFRAME,
    EDITOR_RENDER_MODE_LIT,
    EDITOR_RENDER_MODE_FULLBRIGHT,
    EDITOR_RENDER_MODE_LIGHTING_ONLY,
    EDITOR_RENDER_MODE_COUNT,
};

enum EDITOR_VIEWPORT_FLAGS
{
    EDITOR_VIEWPORT_FLAG_REALTIME               = (1 << 0),
    EDITOR_VIEWPORT_FLAG_GAME_VIEW              = (1 << 1),
    EDITOR_VIEWPORT_FLAG_ENABLE_SHADOWS         = (1 << 2),
    EDITOR_VIEWPORT_FLAG_WIREFRAME_OVERLAY      = (1 << 3),
    EDITOR_VIEWPORT_FLAG_ENABLE_DEBUG_INFO      = (1 << 4),
};

const uint32 EDITOR_ENTITY_ID_RESERVED_BEGIN = 0xFFFFFFF7;


