#pragma once

// Config header for MSVC platforms

// Core defines
#define HAVE_LIBXML2 1
#define HAVE_SQUISH 1
#define HAVE_ZLIB 1
#define HAVE_SFMT 1
#define HAVE_FREEIMAGE 1
#define HAVE_HLSLTRANSLATOR 1

// Engine defines
#define WITH_PROFILER 1
#define WITH_RENDERER_D3D11 1
#define WITH_RENDERER_D3D12 1
#define WITH_RENDERER_OPENGL 1
#define WITH_RENDERER_OPENGLES2 1
#define WITH_RESOURCECOMPILER 1
//#define WITH_RESOURCECOMPILER_EMBEDDED 1
#define WITH_RESOURCECOMPILER_SUBPROCESS 1
#define WITH_RESOURCECOMPILER_STANDALONE 1
#define WITH_MAPCOMPILER 1
#define WITH_MAPCOMPILER_STANDALONE 1
#define WITH_CONTENTCONVERTER 1
#define WITH_CONTENTCONVERTER_STANDALONE 1
#define WITH_IMGUI 1
#define WITH_BASEGAME 1
#define WITH_EDITOR 1
#define WITH_BLOCKENGINE 1
